version: 0.0
os: linux
files:
   - source: /target/jboss-helloworld.war
     destination: /home/ubuntu/wildfly-9.0.1.Final/standalone/deployments
hooks:
  BeforeInstall:
    - location: codeDeployFolder/stopServer.sh
      runas: root
  AfterInstall:
    - location: codeDeployFolder/startServer.sh
      runas: root